### ISSUE TITLE
Add New Dialect: Ukrainian (Python)

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#10]
## Adding Ukrainian to the Legesher Translations for Python
Version 1 of Legesher only includes translations for the Python programming language. In order to add this language to the project, complete the steps detailed in [the translation guide](https://legesher.readme.io/docs/translation-guide)

**To complete this issue**:
- [ ] Create ukrainian dialect `.yml` file
- [ ] Enter translation for _at least_ the Python keywords
- [ ] Merge changes into branch titled `ukrainian-translation` on this repo

### Reviewers Needed
In order to add the translations into our database to use, the translations will need to be approved and accepted by 3 additional native / fluent speakers. If you would like to be one of the reviewers for this language, please mention in this issue! :smile:

**Comment by JekRock** [comment]
@madiedgar Hi!
I'm a native Ukrainian and Russian speaker. Let me know if I can help with translation.

**Comment by madiedgar** [comment]
Hi @JekRock!! This would be amazing 😄! I updated the issue description with a few tips on how to get started, but let me know if you have any questions.

**Comment by Jam-Iko** [comment]
Hi, I am a native Ukrainian speaker. I can contribute to translating or if it is already done, I can help with review.

**Comment by madiedgar** [comment]
That would be amazing @Jam-Iko! 👍 Both would be amazing (as there are quite a few programming languages to translate). Reviewing Python would be the biggest priority right now, but both are encouraged. Feel freet to take a look at the `ukrainian-translation` branch on the repo and add your translations / commentary accordingly 😄

**Comment by JekRock** [comment]
@Jam-Iko I think we need to sync our work just not to do the same task twice. I'll start the Python translation this weekend (sorry, I didn't have time to do it earlier). If you have time before the weekend, you can start the translation, and I'll review it. If you don't, we can do vice versa.

**Comment by Jam-Iko** [comment]
@JekRock I plan to send in translation of keywords tonight and it will be great if you could review it.

**Comment by Jam-Iko** [comment]
@madiedgar, hi! I have stumbled upon an issue. I have been working on a file `uk.yml` that has been created earlier in the `locale` directory, however this file contains only << Keywords >> section, although `language-keyword-template.yml` has additional << Built-In Functions >> block. Should I overwrite the old `uk.yml` file with a new one based on `language-keyword-template.yml`?

**Comment by madiedgar** [comment]
Hey @Jam-Iko  👋! I created a branch `ukrainian-translation` a couple of days ago, but it definitely needs to be updated from the master branch. The file might have an older version of the template, so feel free to add in additional sections that aren't there currently. 👍 So excited for this collaboration!!

**Comment by madiedgar** [comment]
Closing this issue as we are now on reviews! 🎉 thank you @JekRock & @Jam-Iko for your contributions!
