### ISSUE TITLE
Add New Dialect: German (Python)

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#11]
## Adding German to the Legesher Translations for Python
Version 1 of Legesher only includes translations for the Python programming language. In order to add this language to the project, complete the steps detailed in [the translation guide](https://legesher.readme.io/docs/translation-guide)

**To complete this issue**:
- [x] Create german dialect `.yml` file
- [x] Enter translation for _at least_ the Python keywords

### Reviewers Needed
In order to add the translations into our database to use, the translations will need to be approved and accepted by 3 additional native / fluent speakers. If you would like to be one of the reviewers for this language, please mention in this issue! :smile:

**Comment by madiedgar** [comment]
hey @LoLei 👋, have a fun opportunity for you!

**Comment by LoLei** [comment]
Thanks for the notification, I'll keep this in mind, can't promise I can do it quickly though.

**Comment by madiedgar** [comment]
No worries! These translation issues will take a little more time, even if its just the Python keywords! Trying to have more people tackle this with you, so you don't get overwhelmed with the translation. 😄

**Comment by ZeroOne010101** [comment]
Hi! I am a Native speaker from Germany and am looking for things to do for Hacktoberfest.

Just to clarify up front: 
I know nothing about this Project,.
I am self taught so i may not know the correct technical terms.
I am currently very stressed with exams and life in general so i will not be able to work on this on a regular basis.

Now that that's out of the way: Hi, im zero and want to work with you!

**Comment by madiedgar** [comment]
Hi @ZeroOne010101 👋 We're happy to have you here! My hope is that this project isn't another stress to your day, but a form of release and something that brings joy! ✨ 

All of the `legesher` repositories work together in some way. These translations are critical in allowing developers to code in their native language. When version 1 is released, developers will have the ability to take this python function:

``` python
def helloWorld():
  print("Hello World!")
```

and have every aspect of it in their native language - not just the self-named variables, but the keywords as well! 

Our biggest priority this hacktoberfest is translating the python programming language keywords, so we can release our first version of python with as many spoken languages as possible. 

Hope this makes sense 😄 If you have any questions, please feel free to reach out! 👍

**Comment by ZeroOne010101** [comment]
@madiedgar Just one question for now: Should i work towards one big PR , a couple small ones or in a fork and then transfer the final product via PR? 
Im getting started right away!

**Comment by ZeroOne010101** [comment]
Im done with the first pass, some things sound really weird, while others dont really have a translation. should i just keep those in english?

**Comment by madiedgar** [comment]
@ZeroOne010101 great question - what if I create a `german-translation` fork on the repo and you can add incremental pull requests to that specific branch. That way if more people want to add to the translation, they can help on that branch. When the translations get approved, merging the branch into master would mean it's ready to be used across the entire Legseher project!  How does that sound? 😃 

Hmm 🤔, this is what I expected but was curious as to what to do about them. Let's keep them English for now, adding any commentary that would be useful in comments.

**Comment by ZeroOne010101** [comment]
sounds good! im ready to PR whenever you are!

**Comment by madiedgar** [comment]
@ZeroOne010101 awesome!! I made the `german-translation` branch, so feel free to add it there! 😄

**Comment by ZeroOne010101** [comment]
@madiedgar added #12

**Comment by madiedgar** [comment]
Great job @ZeroOne010101, I'm closing this issue as this was resolved in #12 & #15. I'll open up a translation review issue so we can merge in this wonderful work for people to use 👍

**Comment by JohannaHillebrand** [comment]
I reviewed the translation and there are some inconsistencies. In German nouns should have a an uppercase initial letter. Sometimes this is done, sometimes not. 
Also in German you often need to use two words, where only one suffices in English. 
Sometimes those two words are just put together and sometimes CamelCase is used. 
If you guys tell me, what would be preferred, I could change that, so it is more consistent.

**Comment by madiedgar** [comment]
Such interesting facts about the German language! Thank you so much for sharing this! Definitely would be something to discuss further 😄
