### ISSUE TITLE
Issue in py translation

### ISSUE THREAD

**Issue by parammittal16** [legesher/legesher-translations#115]

**Comment by madiedgar** [comment]
This was resolved with [this commit in hindi-translation](https://github.com/legesher/legesher-translations/commit/989ee65bd8258cf58d1fa70d196a2fabe2addcca) and [this commit in gujarati-translation](https://github.com/legesher/legesher-translations/commit/2a8d61419c2d16c93688e5768696adb355a14ff3) 🎉
