### ISSUE TITLE
Add New Dialect: Telugu (Python)

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#127]
## Adding Telugu to the Legesher Translations for Python

In order to add this language to the project, complete the steps detailed in [the translation guide](https://docs.legesher.io/legesher-translations/translation-guide). (We are primarily working developing Legesher for the Python programming language. In the future we hope to add more programming languages.)

**To complete this issue**:

- [x] Update any content in this issue from `LANGUAGE` to the name of the language. (Romanian, Arabic, Welsh etc.)
- [x] Title this issue "Add New Language: Telugu (Python)"
- [ ] Create Telugu dialect `.yml` file with the language abbreviation as the filename
- [ ] Add translations for _at least_ the Python keywords
- [ ] Merge changes into branch titled `telugu-translation` on this repo
- [ ] Add Telugu to `README.md` as languages in progress with a link to the issues with the language's label

**Comment by madiedgar** [comment]
Hey @nagendrady! Here's what you need to get started, let me know if you have any questions 👍

**Comment by madiedgar** [comment]
Hey @nagendrady 👋 , are you still interested in helping with this issue. Would be a great help! 👍

**Comment by nagendrady** [comment]
Hi,yes i am interested.

**Comment by nagendrady** [comment]
hi @madiedgar .Added te.yml file for telugu translation.
