### ISSUE TITLE
💻🍁 Welcome to Hacktoberfest 2020 💻🍁

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#136]
<img width="826" alt="Screen Shot 2020-10-01 at 11 45 35 PM" src="https://user-images.githubusercontent.com/7844510/94886159-35163d00-0440-11eb-8310-717517021b40.png">

# Welcome to [Hacktoberfest](https://hacktoberfest.digitalocean.com/)
..and welcome to our community! So many fun things to get into this Hacktoberfest like [adding translations for your native written language 🌏 ](https://github.com/legesher/legesher-translations), [sharpening & sharing your python skills 🐍 ](https://gtihub.com/legesher/tree-sitter-legesher-python) or even [helping foster our community 📸  by creating instastories or managing our communication channels ❤️](https://github.com/legesher/legesher-pride)!

**Stay in the know**
New issues are added every day with varying difficulty levels for varying skillsets. Get notified of updates by clicking the `👁‍🗨 watch` button and save the repo for later reference by clicking the `⭐️ star` button at the top right corner of this repo! 

## Ways to get involved
Legesher is a growing project with many different ways to get involved. Below is a list of all of the repositories that are participating in Hacktoberfest. You can search by _label_ to find issues that are in the area of your expertise or an area you're wanting to learn / grow in!

| Project | Purpose |
|---------|---------|
| [`tree-sitter-legesher-python`](https://github.com/legesher/tree-sitter-legesher-python) | Tree-sitter python grammar used by text editors allowing Legesher's languages to be implemented |
| [`language-legesher-python`](https://github.com/legesher/language-legesher-python) | Atom's programming language binding to allow syntax highlighting, code folding etc. to a specific grammar |
| [`legesher-translations`](https://github.com/legesher/legesher-translations) |  Host and API of all the language translations for written languages for code keywords / concepts |
| [`legesher-dot-io`](https://github.com/legesher/legesher-dot-io) | Legesher's public [website](https://legesher.io) |
| [`legesher-pride`](https://github.com/legesher/legesher-pride) | Community-focused initiatives to add more value (and members) to our pride |
| [`legesher-docs`](https://github.com/legesher/legesher-docs) | Legesher's documentation hub. Will be transitioning to a documentation host soon. |
| [`legesher`](https://github.com/legesher/legesher) | Git integration to collaborate with code and others in other languages |

### Important Hacktoberfest Information
- Be sure to sign up at [https://hacktoberfest.digitalocean.com](https://hacktoberfest.digitalocean.com) so you can qualify to pick a limited edition t-shirt 👚 or plant a tree!
- Create a Pull Request between October 1-31 of 2020 to count towards your 4 PRs
- See [Contributing Guidelines](https://docs.legesher.io/the-official-things/contributing-guidelines)
- See https://hacktoberfest.digitalocean.com for more details

🎁 If you contribute to a Legesher repository, then you will receive a handwritten letter from our [founder](https://www.instagram.com/withmadico/) expressing her deepest gratitude. You might also find some special edition stickers 👀.

As always, feel free to comment or ask any questions here as well.

**Comment by sebanti10** [comment]
I would love to be a part!

**Comment by Adarwall** [comment]
@madiedgar I can translate javaScript to Hebrew! can you open an issue for that and assign it to me?

**Comment by madiedgar** [comment]
Would love to have y'all! 

@sebanti10 is there a specific language you can help translate? If we aren't currently working on it, would love to start! 

@Adarwall that would be awesome! I created #144 to add Python and the `hebrew-translation` branch for you to add future PR's to. I'm planning on starting Javascript soon across the entire project, so having the Javascript translation from #141 is helpful too! Thank you!

**Comment by syauqy** [comment]
Hi @madiedgar , I can help you with a translation in Bahasa Indonesia. 
You can open an issue for it and assign it to me.

**Comment by madiedgar** [comment]
Awesome, thank you @syauqy 👍 Check out #147

**Comment by Nigar6001** [comment]
Hello, I can help with translation to or from German, English, Turkish, or Azerbaijani. I am a certified user of those languages and also I have a B2 level in Russian but not certified fully yet but if you need help with Russian translation I can help with it.

**Comment by madiedgar** [comment]
That would be lovely @Nigar6001! 🎉 We have current translations in development for [German](https://github.com/legesher/legesher-translations/issues/43), [Turkish](https://github.com/legesher/legesher-translations/issues/174), and [Russian](https://github.com/legesher/legesher-translations/issues/38) that would love another reviewer. We haven't had an Azerbaijani translation yet, but I [created an issue](https://github.com/legesher/legesher-translations/issues/175) for you 👍
