### ISSUE TITLE
Add New Language: Hebrew (Python)

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#144]
## Adding Hebrew to the Legesher Translations for Python

In order to add this language to the project, complete the steps detailed in [the translation guide](https://docs.legesher.io/legesher-translations/translation-guide). (We are primarily working developing Legesher for the Python programming language. In the future we hope to add more programming languages.)

**To complete this issue**:

- [x] Update any content in this issue from `LANGUAGE` to the name of the language. (Romanian, Arabic, Welsh etc.)
- [x] Title this issue "Add New Language: Hebrew (Python)"
- [x] Create Hebrew dialect `.yml` file with the language abbreviation as the filename
- [ ] Add translations for _at least_ the Python keywords
- [ ] Merge changes into branch titled `hebrew-translation` on this repo
- [ ] Add Hebrew to `README.md` as languages in progress with a link to the issues with the language's label

**Comment by madiedgar** [comment]
Hey @Adarwall 👋 Thanks for your interest in contributing to the Hebrew translation. I'll merge in the PR you have created in #141 but would love your help in adding in Python as well!

**Comment by Adarwall** [comment]
@madiedgar I'll do that! assign me plz 😄
