### ISSUE TITLE
Add New Language: Indonesian (Python)

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#147]
## Adding Indonesian to the Legesher Translations for Python

In order to add this language to the project, complete the steps detailed in [the translation guide](https://docs.legesher.io/legesher-translations/translation-guide). (We are primarily working developing Legesher for the Python programming language. In the future we hope to add more programming languages.)

**To complete this issue**:

- [x] Update any content in this issue from `LANGUAGE` to the name of the language. (Romanian, Arabic, Welsh etc.)
- [x] Title this issue "Add New Language: Indonesian (Python)"
- [ ] Create Indonesian dialect `.yml` file with the language abbreviation as the filename
- [ ] Add translations for _at least_ the Python keywords
- [ ] Merge changes into branch titled `indonesian-translation` on this repo
- [ ] Add Indonesian to `README.md` as languages in progress with a link to the issues with the language's label

**Comment by madiedgar** [comment]
Hey @syauqy 👋 Would love your help on this issue 👍

**Comment by syauqy** [comment]
Hi @madiedgar sure, I'll working on it. Thanks 🙏

**Comment by syauqy** [comment]
Hi @madiedgar , please check my PR #154 
A bit confused on the built-in functions. I just put all the literal translation.
Should it be a normal function? Or you need the actual translation?
For example like abs, I translate it to the literal "absolute" meaning.

**Comment by madiedgar** [comment]
@syauqy You bring up a great point, and that's why I value your contribution! Let's start with the full translation of those words and then during the final review process we'll determine how to shorten the word (if that's what is deemed necessary). It might be helpful to keep this in mind: 

> Some translations might be a simple 1:1 exchange, while others may have many ways to describe the keyword. There may no direct translation. In those situations, we encourage you to use your native language to bring to life the fundamentals of programming. Imagine you never learned the english keyword; How would you describe the identifier or process?
