### ISSUE TITLE
Add New Language: Finnish (Python)

### ISSUE THREAD

**Issue by rouskuli** [legesher/legesher-translations#159]
## Adding Finnish to the Legesher Translations for Python

In order to add this language to the project, complete the steps detailed in [the translation guide](https://docs.legesher.io/legesher-translations/translation-guide). (We are primarily working developing Legesher for the Python programming language. In the future we hope to add more programming languages in the future.)

**To complete this issue**:

- [x] Update any content in this issue from `LANGUAGE` to the name of the language. (Romanian, Arabic, Welsh etc.)
- [x] Title this issue "Add New Language: LANGUAGE (Python)"
- [x] Create LANGUAGE dialect `.yml` file with the language abbreviation as the filename
- [x] Add translations for _at least_ the Python keywords
- [x] Merge changes into branch titled `LANGUAGE-translation` on this repo

**Comment by rouskuli** [comment]
Could someone create the `finnish-translation` branch in this repo? The Python keywords are translated already! :)

**Comment by madiedgar** [comment]
Thank you so much for starting this @rouskuli 🎉 I created the `finnish-translation` branch for you.
