### ISSUE TITLE
Page not found language-conventions

### ISSUE THREAD

**Issue by wang-ories** [legesher/legesher-translations#16]
Hi!
I found that this link [https://github.com/legesher/legesher/blob/master/.github/language-conventions.md](url) is not working. The file **language-conventions.md** is not found.

**Comment by madiedgar** [comment]
Oooh! Thank you so much for finding this 🙈I definitely did not commit the file. I'll add this to the repo 👍

**Comment by madiedgar** [comment]
Hey @wang-ories 👋 I finally got the file added to the repository, but it's in a different location than described in the link. Would you mind updating the `README.md` in this repo with the new link?

`https://github.com/legesher/legesher/blob/master/LANGUAGE_CONVENTIONS.md`

**Comment by wang-ories** [comment]
> Hey @wang-ories 👋 I finally got the file added to the repository, but it's in a different location than described in the link. Would you mind updating the `README.md` in this repo with the new link?
> 
> `https://github.com/legesher/legesher/blob/master/LANGUAGE_CONVENTIONS.md`

Ok @madiedgar, I can take this up.

**Comment by wang-ories** [comment]
Hi @madiedgar, I created a PR here #94.

**Comment by madiedgar** [comment]
Closing this as it was resolved in #94 🎉
