### ISSUE TITLE
Add New Language: Greek (Python)

### ISSUE THREAD

**Issue by ioannouE** [legesher/legesher-translations#162]
## Adding Greek to the Legesher Translations for Python

In order to add this language to the project, complete the steps detailed in [the translation guide](https://docs.legesher.io/legesher-translations/translation-guide). (We are primarily working developing Legesher for the Python programming language. In the future we hope to add more programming languages in the future.)

**To complete this issue**:

- [ ] Update any content in this issue from `LANGUAGE` to the name of the language. (Romanian, Arabic, Welsh etc.)
- [ ] Title this issue "Add New Language: Greek (Python)"
- [ ] Create Greek dialect `.yml` file with the language abbreviation as the filename
- [ ] Add translations for _at least_ the Python keywords
- [ ] Merge changes into branch titled `Greek-translation` on this repo

**Comment by madiedgar** [comment]
This is great @ioannouE ! 👍 I'll add a `greek-translation` branch for you to merge your changes into!
