### ISSUE TITLE
Add Swahili to Active Development in README

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#192]
## Add Swahili to Active Development in README

In [this section](https://github.com/legesher/legesher-translations#languages-in-active-development) of the README, there is a list of languages we are currently developing in. 

Please add Swahili to the list of languages in active development.

**To complete this issue**
- [ ] Update the README to include the list of dialects in development, keeping the list in alphabetical order.
  - You can find these by looking at the branches in this repository that read `DIALECT-translation`. Every one of those dialects should be added to this list. 
- [ ] Please add each of the items in the list as links to the issues / pr that have that dialect label. 
  - For example, this is the link for the [`Dialect: German`](https://github.com/legesher/legesher-translations/issues?q=label%3A%22Dialect%3A+German%22) label.

**Comment by wambugucoder** [comment]
i wouldnt mind doing this 😄

**Comment by madiedgar** [comment]
Awesome, I'll assign you to it 👍  Let me know if you have any questions!

**Comment by wambugucoder** [comment]
Should i merge it with the main branch?

**Comment by madiedgar** [comment]
@wambugucoder Yes, please do. My apologies for not mentioning!

**Comment by wambugucoder** [comment]
Done
