### ISSUE TITLE
🍂 💻 Welcome to Hacktoberfest 2021 🍂💻 

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#214]
<img width="826" alt="banner08CRredlogo" src="https://user-images.githubusercontent.com/7844510/135486878-738f39ab-f7a3-4816-9eed-efef2915d0ce.png">

# Happy [Hacktoberfest](https://hacktoberfest.digitalocean.com/)
..and welcome to our community! This is our third Hacktoberfest and we're excited for what we'll build together! So many fun things to get into this Hacktoberfest like [adding translations for your native written language 🌏 ](https://github.com/legesher/legesher-translations), [sharpening & sharing your python skills 🐍 ](https://gtihub.com/legesher/tree-sitter-legesher-python) or even [helping foster our community 📸  by creating content or managing our communication channels ❤️](https://github.com/legesher/legesher-pride)!

### Stay in the know
**🆕 New Issues** 
New issues are added every week with varying difficulty levels for diverse skill sets. Get notified of updates by clicking the `👁‍🗨 watch` button and save the repo for later reference by clicking the `⭐️ star` button at the top right corner of this repo! We also will tweet every new issue as it comes out, so [follow us @ legesherio 🐣](https://twitter.com/legesherio).

**⏰ Office Hours**
This Hacktoberfest, we will be hosting office hours on our [discord](https://discord.gg/DkVjVDP) on Saturdays at 10am EST. Come with any questions about Legesher, contributing on GitHub, or anything else open source. 

## Ways to get involved
Legesher is a growing project with many different ways to get involved. Below is a list of all of our repositories that are participating in Hacktoberfest. You can search by _label_ to find issues that are in the area of your expertise or an area you're wanting to learn / grow in! If you'd like to contribute in ways that might not fit within these repos, comment your ideas below! 

| Project | Purpose |
|---------|---------|
| [`tree-sitter-legesher-python`](https://github.com/legesher/tree-sitter-legesher-python) | Tree-sitter python grammar used by text editors allowing Legesher's languages to be implemented |
| [`language-legesher-python`](https://github.com/legesher/language-legesher-python) | Atom's programming language binding to allow syntax highlighting, code folding etc. to a specific grammar |
| [`legesher-translations`](https://github.com/legesher/legesher-translations) |  Host and API of all the language translations for written languages for code keywords / concepts |
| [`legesher-dot-io`](https://github.com/legesher/legesher-dot-io) | Legesher's public [website](https://legesher.io) |
| [`legesher-pride`](https://github.com/legesher/legesher-pride) | Community-focused initiatives to add more value (and members) to our pride |
| [`legesher-docs`](https://github.com/legesher/legesher-docs) | Legesher's documentation hub. Will be transitioning to a documentation host soon. |
| [`legesher`](https://github.com/legesher/legesher) | Git integration to collaborate with code and others in other languages |

### Goals
1.  `legesher-translations`: Develop API for translations of keywords (with documentation)
2.  `tree-sitter-legesher-python` & `language-legesher-python` : Incorporate translation API to support language translations for Python programming in Atom
3.  `legesher-translations` : Progress in the development of translations in Python
  - 50 languages in the Preparation Phase (_currently 32_)
  - 35 languages in the Active Development Phase (_currently 20_)
  - 10 languages in the Final Review Phase (_currently 2_)
  - 4 languages accepted as official translations 

### Important Hacktoberfest Information
- Be sure to sign up at [https://hacktoberfest.digitalocean.com](https://hacktoberfest.digitalocean.com) so you can qualify to pick a limited edition t-shirt 👚 or plant a tree!
- Create a valid Pull Request between October 1-31 of 2021 to count towards your 4 PRs
- See [Contributing Guidelines](https://docs.legesher.io/the-official-things/contributing-guidelines)
- See https://hacktoberfest.digitalocean.com for more details
- Subscribe to our [newsletter](https://mailchi.mp/083d8b2e0e12/legesher-landing-page)  

🎁 If you contribute to a Legesher repository, then you will receive a handwritten letter from our [founder](https://www.instagram.com/withmadico/) expressing her deepest gratitude. You might also find some special edition stickers 👀.

As always, feel free to comment or ask any questions here as well.

**Comment by natastro** [comment]
Hi @madiedgar ! Could I add an `es.yml` file with translations? 😊

**Comment by natastro** [comment]
Hi @madiedgar ! Are we still able to continue contributing with translations? I've been preoccupied this week with grad school homework but would love to keep working on this this weekend 😊 thank you!

**Comment by madiedgar** [comment]
Absolutely @natastro! Always happy to accept translation reviews. Let me know if you have any questions 👍
