### ISSUE TITLE
Add New Language: Finnish (Java)

### ISSUE THREAD

**Issue by minna-xD** [legesher/legesher-translations#242]
## Adding Finnish to the Legesher Translations for Java

In order to add this language to the project, complete the steps detailed in [the translation guide](https://docs.legesher.io/legesher-translations/translation-guide).

**To complete this issue**:

- [x] Update any content in this issue from `LANGUAGE` to the name of the language. (Romanian, Arabic, Welsh etc.)
- [x] Title this issue "Add New Language: LANGUAGE (Python)"
- [x] Create LANGUAGE dialect `.yml` file with the language abbreviation as the filename  [file already created for Python]
- [x] Add translations for _at least_ the Java keywords
- [x] Merge changes into branch titled `Finnish-translation` on this repo

**Comment by madiedgar** [comment]
This was resolved in #243 🎉
