### ISSUE TITLE
Add New Language: Hebrew (JavaScript)

### ISSUE THREAD

**Issue by TomerPacific** [legesher/legesher-translations#260]
## Adding Hebrew to the Legesher Translations for JavaScript

In order to add this language to the project, complete the steps detailed in [the translation guide](https://docs.legesher.io/legesher-translations/translation-guide). (We are primarily working developing Legesher for the Python programming language. In the future we hope to add more programming languages in the future.)

**To complete this issue**:

- [x] Update any content in this issue from `LANGUAGE` to the name of the language. (Romanian, Arabic, Welsh etc.)
- [x] Title this issue "Add New Language: Hebrew(JavaScript)"
- [x] Create Hebrew dialect `.yml` file with the language abbreviation as the filename
- [ ] Add translations for _at least_ the JavaScript keywords
- [ ] Merge changes into branch titled `hebrew-translation` on this repo

**Comment by madiedgar** [comment]
Thank you @TomerPacific, looking forward to your PR 👍
