### ISSUE TITLE
marketing: add repository to "awesome-for-non-programmers"

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#3]
## Awesome-For-Non-Programmers

Would love to add this repository to the [`awesome-for-non-programmers`](https://github.com/szabgab/awesome-for-non-programmers) repository for non programmers to learn about open source opportunities that don't require a technical background. 

With the Legesher project, there are a lot of opportunities for people of all backgrounds to contribute the skills they either want to grow in or give back. With a strong emphasis on written language translation, individuals who are bilingual have a great space to contribute. Individuals who want to grow in community development, marketing, writing impactful pieces of insight, or just want to learn more about the tech world have ample amounts of opportunities here as well! 

More details can be found in their pull request template.

**Comment by fernandasj** [comment]
Are you referring to adding this repo to the table in the Legesher Projects section?

**Comment by madiedgar** [comment]
The other way around! This would involve making a pull request in the `awesome-for-non-programmers` repository to include the `legesher-translations` repository. There should be some other pull requests from other Legesher contributors (see [#20](https://github.com/szabgab/awesome-for-non-programmers/pull/20) and [#19](https://github.com/szabgab/awesome-for-non-programmers/pull/19))

**Comment by fernandasj** [comment]
I understood!! Should the pull request text be the same as the issue?

**Comment by madiedgar** [comment]
Oh! Yes - that would be wonderful! 😄 Thank you!!

**Comment by fernandasj** [comment]
YAY!! Ok :heart:

**Comment by fernandasj** [comment]
[Pull Request Resolves](https://github.com/szabgab/awesome-for-non-programmers/pull/27) :heart:

**Comment by madiedgar** [comment]
Amazing!! Thank you so much! I'm going to close this issue. Please be sure to fill out [this form](https://madi357705.typeform.com/to/wzub4R) so I can formally thank you for your contribution.  🎉

**Comment by fernandasj** [comment]
I answered the form right now !! :heart: thank you!
