### ISSUE TITLE
Add New Dialect: Spanish (Python)

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#30]
## Adding Spanish to the Legesher Translations for Python
Version 1 of Legesher only includes translations for the Python programming language. In order to add this language to the project, complete the steps detailed in [the translation guide](https://legesher.readme.io/docs/translation-guide)

**To complete this issue**:
- [ ] Create Spanish dialect `.yml` file
- [ ] Enter translation for _at least_ the Python keywords
- [ ] Merge changes into branch titled `spanish-translation` on this repo

### Reviewers Needed
In order to add the translations into our database to use, the translations will need to be approved and accepted by 3 additional native / fluent speakers. If you would like to be one of the reviewers for this language, please mention in this issue and you'll be notified when the review is ready! :smile:

**Comment by zoomstereo** [comment]
Hi, I'm a native Spanish speaker, I would like to work on the Spanish translations, I'm wondering if I can do a pull with partial translation of the template or I must do the full template translation to commit?

**Comment by madiedgar** [comment]
Hey @zoomstereo 👋! Would love to have you join us! Our biggest priority right now is with translating _Python_. If you would be able to lead the translation of that programming language, that would be amazing! 

Please use the full template file when creating the spanish dialect `.yml` file, but feel free to skip to the Python section and translate those keywords / builtin functions. If there is a term you do not know, leaving the english translation in the placeholder and a comment as to your thoughts would be helpful for the reviewers. 

Let me know if you have any questions!

**Comment by asperduti** [comment]
Hi! @madiedgar  Can I made a contribution to this? Improving something of the job done by @zoomstereo and maybe another issue/pr for the C language? I'm a native Spanish speaker.
This will be my first contribution to a project.

**Comment by madiedgar** [comment]
Amazing @asperduti! Happy to have you! 

I just added #37 for reviewing the Python translation for Spanish. That might be a great place to start and then tackle another issue/pr after for C. 👏

**Comment by madiedgar** [comment]
Closing this issue as we are now onto reviews ! 🎉  thank you @zoomstereo and @asperduti for your contribtions!
