### ISSUE TITLE
Add New Dialect: Welsh (Python)

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#32]
## Adding Welsh to the Legesher Translations for Python
Version 1 of Legesher only includes translations for the Python programming language. In order to add this language to the project, complete the steps detailed in [the translation guide](https://legesher.readme.io/docs/translation-guide)

**To complete this issue**:
- [ ] Create Welsh dialect `.yml` file
- [ ] Enter translation for _at least_ the Python keywords
- [ ] Merge changes into branch titled `welsh-translation` on this repo

### Reviewers Needed
In order to add the translations into our database to use, the translations will need to be approved and accepted by 3 additional native / fluent speakers. If you would like to be one of the reviewers for this language, please mention in this issue and you'll be notified when the review is ready! :smile:

**Comment by madiedgar** [comment]
Hey @ajtrichards, what about this? 😄

**Comment by ajtrichards** [comment]
I’ll take this one :)

**Comment by madiedgar** [comment]
Awesome @ajtrichards, I'll assign you to it!

**Comment by madiedgar** [comment]
Closing this as it was resolved by @ajtrichards in #98. 🎉
