### ISSUE TITLE
Review Dialect: Spanish (Python)

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#37]
## Review Spanish Language Translations for the Python Programming Language

In order to review this language to the project, complete the steps detailed in the [translation guide](https://docs.legesher.io/legesher-translations/translation-guide) (from Step # 6 onward). We are primarily working developing Legesher for the Python programming language. In the future we hope to add more programming languages.

**Reviewing** a translation is extremely important as we want to best understand the culture and context behind the words we select as keywords for the programming languages. The more perspectives the better! 👀Please take your time in being thorough with these translations. Think back when you were learning how to program and how context of words help you bridge together meaning and functionality.

> ⚠️ Note: this issue is to review the Python keywords and builtin functions only. Any additional translation reviews are encouraged, but not necessary.

**To complete this issue**:
- [x] Update any content in this issue from `Spanish` to the name of the language. (Romanian, Arabic, Welsh etc.)
- [x] Title this issue "Review Language: Spanish (Python)"
- [x] Update the Python section of the Spanish's `locale/__.yml` file (files are named using the language abbreviation) by adding comments as followed:
  - Leave a `✅`after a translation if you agree that's the right word to give context to the keyword
  - Leave a `❓` after a translation if you think there may be a better translation / form of the translation
  - Leave a `🤔` after a word that you're not sure if there is a translation
- [x] Merge changes into branch titled `spanish-translation` on this repo. Please reference this issue in the pull request.

### Reviewers Needed

In order to add the translations for official use across Legesher, the translations will need to be approved and accepted by __5 additional native / fluent speakers__. If you would like to be one of the reviewers for this language, please mention in this issue! :smile: Also feel free to loop in a friend that might be able to help with the translations! Please refer to the [translation guide](https://docs.legesher.io/guide/contributor/translation-guide) for the next step in the review process.

**Review Status:**
- [x] `Add New Dialect` Issue (#30)
- [x] Initiator: @zoomstereo (#35)
- [x] Reviewer 1: @asperduti (#45)
- [x] Reviewer 2: @reegoram (#77)
- [x] Reviewer 3: @kararade (#79)
- [x] Reviewer 4: @JJgar2725 (#134)
- [x] Reviewer 5: @aliciacisnerosm (#138)
- [ ] Reviewer 6: @divae
- [x] Reviewer7: @iam-agf (#145)
- [ ] Reviewer 8: @hesau2001
- [ ] Reviewer 9: @zayle
- [x] Reviewer 10: @begeistert (#180)

**Comment by reegoram** [comment]
Hello @madiedgar, I'd like to contribute with the revision as well 😄
I'm native Spanish speaker.

**Comment by madiedgar** [comment]
That would be amazing @reegoram!! 🎉

**Comment by kararade** [comment]
hey @madiedgar I would like to contribute as well, I'm a native Spanish speaker too 😆

**Comment by kararade** [comment]
I have this ready!

**Comment by madiedgar** [comment]
Awesome @kararade! Happy to have you!

**Comment by JJgar2725** [comment]
Hello, @madiedgar! I'm familiar with this language and would be happy to contribute by reviewing.

**Comment by JJgar2725** [comment]
#134

**Comment by madiedgar** [comment]
Hey @hesau2001, this would be a great place to start 👍🏾 We need to finalize this translation and having your review would be truly helpful

**Comment by madiedgar** [comment]
Hey @JJgar2725, @kararade, @reegoram, @asperduti, @zoomsttereo 👋 , thanks so much for helping with adding to the Spanish translation. Do you know anyone else who might be interested in contributing to this? Thank you 👍 

Hey @hesau2001 👋 , are you still interested in helping with this issue. Would be a great help! 👍

**Comment by aliciacisnerosm** [comment]
hi @madiedgar , I'd like to contribute to the revision (:

**Comment by divae** [comment]
hi @madiedgar , I'm native and I'd like to contribute to the revision ^^

**Comment by madiedgar** [comment]
Amazing @aliciacisnerosm and @divae! The more reviewers the better 👍 Let me know if you have any questions in making your PR.

**Comment by iam-agf** [comment]
Can I help here too? I'm native Spanish speaker.

**Comment by madiedgar** [comment]
Absolutely @iam-agf! 👍

**Comment by iam-agf** [comment]
@madiedgar the link for the translation guide is broken, does exist another? 

Also, the way the PR's are done is ordered?

**Comment by hesau2001** [comment]
> Hey @JJgar2725, @kararade, @reegoram, @asperduti, @zoomstereo wave , thanks so much for helping with adding to the Spanish translation. Do you know anyone else who might be interested in contributing to this? Thank you +1
> 
> Hey @hesau2001 wave , are you still interested in helping with this issue. Would be a great help! +1

Yea sure. Where I begin?

**Comment by marcodeanda** [comment]
Hello @madiedgar! Could I help?

**Comment by zayle** [comment]
Is still active this issue? I would like to help here.

**Comment by madiedgar** [comment]
Thanks for the catch @iam-agf, I updated the link with the correct url 👍

**Comment by begeistert** [comment]
Hello @madiedgar, Can I still help here? I'm native Spanish speaker.

**Comment by madiedgar** [comment]
Yes @begeistert, would love your help! Let me know if you have any questions.

**Comment by madiedgar** [comment]
Closing this as we are now starting the official translation!! 🎉
