### ISSUE TITLE
Review Dialect: German (Python)

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#43]
## Review German Language Translations for the Python Programming Language

In order to review this language to the project, complete the steps detailed in the [translation guide](https://docs.legesher.io/legesher-translations/translation-guide) (from Step # 6 onward). We are primarily working developing Legesher for the Python programming language. In the future we hope to add more programming languages.

**Reviewing** a translation is extremely important as we want to best understand the culture and context behind the words we select as keywords for the programming languages. The more perspectives the better! 👀Please take your time in being thorough with these translations. Think back when you were learning how to program and how context of words help you bridge together meaning and functionality.

> ⚠️ Note: this issue is to review the Python keywords and builtin functions only. Any additional translation reviews are encouraged, but not necessary.

**To complete this issue**:
- [x] Update any content in this issue from `German` to the name of the language. (Romanian, Arabic, Welsh etc.)
- [x] Title this issue "Review Language: German (Python)"
- [x] Update the Python section of the German's `locale/__.yml` file (files are named using the language abbreviation) by adding comments as followed:
  - Leave a `✅`after a translation if you agree that's the right word to give context to the keyword
  - Leave a `❓` after a translation if you think there may be a better translation / form of the translation
  - Leave a `🤔` after a word that you're not sure if there is a translation
- [x] Merge changes into branch titled `german-translation` on this repo. Please reference this issue in the pull request.

### Reviewers Needed

In order to add the translations for official use across Legesher, the translations will need to be approved and accepted by __5 additional native / fluent speakers__. If you would like to be one of the reviewers for this language, please mention in this issue! :smile: Also feel free to loop in a friend that might be able to help with the translations! Please refer to the [translation guide](https://docs.legesher.io/guide/contributor/translation-guide) for the next step in the review process.

**Review Status:**
- [x] `Add New Dialect` Issue (#11)
- [x] Initiator: @zeroone010101 (#12, #13)
- [x] Reviewer 1: @lolei (#15)
- [x] Reviewer 2: @nausicaea (#64)
- [x] Reviewer 3: @otherpaco (#65)
- [ ] ~~Reviewer 4: @twille00 (#64)~~
- [x] Reviewer 5: @johannahillebrand (#101)
- [x] Reviewer 6: @merelyanna (#105)
- [x] Reviewer 7: @diana48 (#118)
- [x] Reviewer 8: @alxnull (#146)

**Comment by JohannaHillebrand** [comment]
Do you still need help with reviewing the translations? I'm a native-german-speaker and would like to contribute :)

**Comment by madiedgar** [comment]
Yes @JohannaHillebrand! Still looking for reviewers for this repo!

**Comment by merelyAnna** [comment]
I am also a native-german speaker and am happy to help out if more help is needed :)

**Comment by JohannaHillebrand** [comment]
If I agree with an alternative suggestion someone made, should I change that one or put a ✅ behind the alternative? I'm just asking, because this might get quite messy.. ;)

**Comment by diana48** [comment]
Do you still need someone to review? I'm also a native German speaker and would love to help out!

**Comment by madiedgar** [comment]
Yes @diana48, that would be amazing!! 👍

**Comment by alxnull** [comment]
Just found this promising looking project. Seems like German already reached the required amount of reviewers, or would you still accept another review? :)

**Comment by madiedgar** [comment]
Hey @alxnull 👋 Thanks for your interest! Would love to finalize the python translation and would really appreciate your help with that. 👍

**Comment by alxnull** [comment]
Hey @madiedgar,

Just to clear things up for me 😅: Should I do another review or does "finalizing the Python translation" mean step 8 of the [translation guide](https://docs.legesher.io/legesher-translations/translation-guide)? How would I approach this? Open a new PR to master with a final version of the German translation, taking all reviewer comments into account and highlighting translations that are still controversial/ unclear for further discussion?

**Comment by madiedgar** [comment]
Great question @alxnull 👍 if you could be the last reviewer for python that would be great. After your PR is merged, I'll create another issue for officially finalizing the python translation where all of the previous contributors will be looped in.

**Comment by madiedgar** [comment]
Closing this issue, as we are now preparing for the official translation in #184 🎉
