### ISSUE TITLE
Am I going crazy or is this repo empty?

### ISSUE THREAD

**Issue by LoLei** [legesher/legesher-translations#6]
I'd like to contribute, but I can't find a `guide` directory in this repo as described in the Readme, or anything apart from the GitHub bot files. Am I blind, or is this just still in the process of being set up for Hacktoberfest?

**Comment by madiedgar** [comment]
Hi @LoLei 👋, thanks so much for reaching out and wanting to contribute! Thank you so much for your patience, for this repository is still being prepped for Hacktoberfest. In the meantime, what are some areas you are wanting to contribute / grow / learn? I'll keep you in mind as I'm preparing issues 😄

**Comment by LoLei** [comment]
Okay, that's what I was thinking. I could definitely provide translations for German, and whatever there is to do in Python I'll check out too!

**Comment by madiedgar** [comment]
That would be AMAZING @LoLei!! I'll let you know when there are things in the pipeline for you 😄
