### ISSUE TITLE
docs: update README with new project list

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#7]
## Update README with new project list

Yay for updated documentation! We added a new repository just for non-programmers and thus need to update our repositories project list with the new information! 🎉 

The [Legesher Projects](https://github.com/legesher/legesher-translations#legesher-projects) section of the README needs to be updated in the following ways:

- [ ] Add the `legesher-pride` repository as a row in the table
  - [ ] Follow the table conventions introduced by the other row items
  - [ ] Add the description: `a non-programmer's dream to contributing to open source by sharing what they know and learning what's new`

**Comment by fernandasj** [comment]
I'm working this :heart:

**Comment by madiedgar** [comment]
Amazing!! I'll assign you to this 😄

**Comment by fernandasj** [comment]
I submitted a pull request :smile:
