### ISSUE TITLE
Add Current Languages in Development to README

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#88]
## Add New Languages to Current Development in README

Hacktoberfest has been AMAZING and we've started a lot of development for new languages! It's about time to update our README to include such amazing progress! 

In [this section](https://github.com/legesher/legesher-translations#languages-in-active-development) of the README, there is a list of languages we are currently developing in. 

**To complete this issue**
- [x] Update the README to include the list of dialects in development.
  - You can find these by looking at the branches in this repository that read `DIALECT-translation`. Every one of those dialects should be added to this list.
- [x] Please add each of the items in the list as links to the issues / pr that have that dialect label. 
  - For example, this is the link for the [`Dialect: German`](https://github.com/legesher/legesher-translations/issues?q=label%3A%22Dialect%3A+German%22) label.

**Comment by annahayhurst** [comment]
Hi! I would be happy to work on this 😄

**Comment by madiedgar** [comment]
That would be amazing @annahayhurst 👏 I'll assign you to it!

**Comment by daya2940** [comment]
i would also like to work on this

**Comment by madiedgar** [comment]
Hey @daya2940 👋 Thanks for wanting to contribute! I forgot to close this issue, as it was resolved by @annahayhurst in #89.  🙊 Keep a look out on future issues though! 👍
