### ISSUE TITLE
Add New Dialect: Portuguese (Python)

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#9]
## Adding Portuguese to the Legesher Translations for Python
Version 1 of Legesher only includes translations for the Python programming language. In order to add this language to the project, complete the steps detailed in [the translation guide](https://legesher.readme.io/docs/translation-guide)

### Reviewers Needed
In order to add the translations into our database to use, the translations will need to be approved and accepted by 3 additional native / fluent speakers. If you would like to be one of the reviewers for this language, please mention in this issue! :smile:

**Comment by madiedgar** [comment]
This is a translation from Davi via email (we're still introducing him to GitHub :smile:)

Truth Values
	•	  True- adjetivo/nome: verdade: verdadeiro / exato, fiel / certo. Adjective/noun: true: trustworthy, trustful/ exact, faithful/ correct.
	•	  False- adjetivo: falso, ilusório / vão / vazio de significado / enganoso, enganador / plagiado / mentiroso / artificial / inconfiável. adjective: false, illusory/ vain/ empty meaning/deceptive, deceiving/ plagiarized/ liar/ artificial/ unreliable.
Logical Operators
	•	  and: conjunção:  também / e, junto com. conjuction: also/ and, together with.
	•	  not: advérbio: não - ou algo relacionado à negativo. adverb: not, no- related to negative.
	•	  or : conjunção: ou - algo equivalente, alternativo ou substituto. conjunction: between two things of equal value, alternative or substitute.
Loops
	•	  for : preposição: para, com o intuito de / por / pelo / durante / apesar de / quanto a / a favor / em relação / por causa / em troca. Preposition: for, in order to/ due to, by, in/ during/ even though, in spite of, nevertheless.
	•	  in : preposição: em / dentro de. Preposition: in the, on the/ inside of.
	•	  while :  conjunção: enquanto / na hora que, no tempo que, na época que . Conjuction: while, in the meantime.
	•	  if - conjunção: se / possibilidade / condição. Conjunction: se(a particle used as direct object)/ possiblity/ condition.
	•	  elif:
	•	  else: adjetivo: Outro além das opções mencionadas anteriormente. Adjective; Other; in addition to previously mentioned items.
	•	  break: nome: Verbo: quebrar / romper / violar / interromper. Verb: time out, fracture/ to break in, to break down, "invade"/ violate/ interrupt.\
	•	continue: verbo: continuar/ manter algo em movimento progressivo. keep or maintain in unaltered condition; cause to remain or last.
User Defined Structures
	•	  class: nome: classe / departamento, classe (também em informática) / posição / (Informática) definição dos atributos e funções de um tipo de objeto/ Aula. Noun: class/ department, class (also in computer science)/ position/ definition of attribute, quality or function of an object.
	•	  def
	•	  async
	•	  await: verbo: aguardar / esperar. look forward to the probable occurrence of
References
	•	  del
	•	  as: conjunção: a medida que / em relação a. Advérbio: como / enquanto / conforme. Conjunction: according as/ in relation to. Adverb: like, in the meantime/ depending on.
	•	  is: verbo: ser / estar / ficar, ocupar um espaço / ocorrer, acontecer / existir. Verb: be/ stay in a space/ occurring, happening/ existing.
	•	 none: pronome: nada / ninguém / de jeito nenhum. Advérbio: nenhum / de forma alguma. Pronoun: nothing, anything/ no one, nobody/ no way.
Exceptions
	•	  except: Preposicao: exceto, menos / menos que. Conjunção: a não ser que. Verbo: excluir. Preposition: except, but, less. Verb: exclude.
	•	  try: verbo: tentar / testar /. Nome: tentativa / teste. Verb: to try, to attempt, to tempt
	•	  raise: nome: aumento / elevação / levantamento. Verbo: levantar / construir /. Noun: increase/ elevated/ lift. Verb: lift/ construct/.
	•	  finally: advérbio: finalmente, no final / enfim, até que enfim. Adverb: finally, in the end.
Module Abstractions
	•	  from: preposição: de / desde. Preposition: of/ from somewhere else.
	•	  import: nome: importação (também em informática) / (informática) carregamento de arquivo que foi criado por um programa num outro programa. Verbo: importar, trazer do exterior. Noun: import (computer science)/ upload archive or file created by one sotweare to another one (computer science).
Variable Declarations
	•	  global: adjetivo: global / integral / total. Adjective: global/ complete, integral/ total.
	•	  lambda
	•	  nonlocal
Function Properties
	•	  pass: verbo: passar / transmitir / deixar, permitir. Verbo: passagem, caminho / aprovar. Verb: pass/ to transmit, to convey, broadcast (TV)/ to allow, to permit./ access, passageway/ to approve.
	•	  return: nome/adjetivo: volta / retorno / espaço / (informática) tecla return ou enter. Verbo: devolver / retorno / regressar. Noun/ adjective: comeback./ return or enter key (computer science)/ give back, go back.
	•	  with: preposição: com/ com respeito à. Preposition: with.
	•	  yield: verbo: render-se, capitular / render frutos, dar lucro / recuar. Nome: produção, safra / renda, lucro. Verb: surrender, capitulate/ yield fruits, profit/ to back up, to move back.
Debugging
	•	  assert: verbo: afirmar, declarar, expressar / insistir (num ponto de vista). Verb: to affirm, to declare, to express/ insist (in a point of view).

**Comment by katherinefernandes** [comment]
Hey! I am new to open source programming. I forked the repository and cloned it so it could be in my desktop. I already changed some things in the file pt.yml. I can add Davi's translations as well, but I have a queston: How are you able to see my changes? Thanks in advance!

**Comment by madiedgar** [comment]
Hey @katherinefernandes 👋, welcome to the wonderful world of open source! This would be really helpful! 👏, I'm going to assign you to this issue and change the status to `accepted`. 

Next steps would go something like this:
- You'll want to create a branch within your forked repository
-  Commit those changes you just made to the branch ^
- Create a **pull request** on this repository comparing your forked branch (with changes) to the `portuguese-translations` branch of this repository. 

When you do that, I'll be able to see your updates and if we need to update anything we can talk through it line by line in the pull request (it's actually pretty cool 👍 😎)

Let me know if I can help explain any aspect of this further!

**Comment by geraldobraz** [comment]
Hi @madiedgar may I try to solve this issue too?

**Comment by madiedgar** [comment]
Hey @geraldobraz 👋!  We would greatly appreciate that! I just merged @katherinefernandes's updates to the `portuguese-translation` branch so please feel free to complete this issue there! 👍 Let me know if you have any questions!

**Comment by geraldobraz** [comment]
@madiedgar What do you expect to be done on the pt.yml file? Just a "simple" translate like:
"Hi": "Oi" or a full translate?

**Comment by madiedgar** [comment]
Hey @geraldobraz 👋 I'll update the issue description, but a simple translation is fine! The only programming language we _need_ now is Python, but feel free to do more. We might do a simple way to translate duplicates in later issues. 👍

**Comment by geraldobraz** [comment]
@madiedgar I just made a PR to check if the translations are the way you expect to be done  😄. Also, you wrote in the issue that reviewers are needed, I'm native so may I help you wit that?

**Comment by madiedgar** [comment]
Closing this issue as we are now on to reviews! 🎉 thanks @geraldobraz, @katherinefernandes and @fayhen for your contributions!
