### ISSUE TITLE
Add New Dialect: Hindi (Python)

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#91]
## Adding Hindi to the Legesher Translations for Python
Version 1 of Legesher only includes translations for the Python programming language. In order to add this language to the project, complete the steps detailed in [the translation guide](https://legesher.readme.io/docs/translation-guide)

**To complete this issue**:
- [ ] Create Hindi dialect `.yml` file
- [ ] Enter translation for _at least_ the Python keywords
- [ ] Merge changes into branch titled `hindi-translation` on this repo

### Reviewers Needed
In order to add the translations into our database to use, the translations will need to be approved and accepted by 3 additional native / fluent speakers. If you would like to be one of the reviewers for this language, please mention in this issue and you'll be notified when the review is ready! :smile:

**Comment by parammittal16** [comment]
@madiedgar can i take this ?

**Comment by madiedgar** [comment]
Absolutely @parammittal16! That would be amazing!! 👏

**Comment by kichloo** [comment]
@madiedgar Can I work on it parallely too and I want to become the reviewer for Hindi language.
Thanks

**Comment by madiedgar** [comment]
That would be lovely @kichloo! After @parammittal16 submits the initial translation, then you can get going on reviewing the Python language keywords / built-in functions and/or adding new language translations to be reviewed 😄 I'll create a "Review Dialect: Hindi (Python)" issue with more information once this is merged in!

**Comment by kichloo** [comment]
Ok!

**Comment by madiedgar** [comment]
🎉 YAY we now have the initial hindi translations available thanks to @parammittal16 👏 Time to start a review issue 👍
