### ISSUE TITLE
Add New Dialect: Gujarati (Python)

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#92]
## Adding Gujarati to the Legesher Translations for Python
Version 1 of Legesher only includes translations for the Python programming language. In order to add this language to the project, complete the steps detailed in [the translation guide](https://legesher.readme.io/docs/translation-guide)

**To complete this issue**:
- [ ] Create Gujarati dialect `.yml` file
- [ ] Enter translation for _at least_ the Python keywords
- [ ] Merge changes into branch titled `gujarati-translation` on this repo

### Reviewers Needed
In order to add the translations into our database to use, the translations will need to be approved and accepted by 3 additional native / fluent speakers. If you would like to be one of the reviewers for this language, please mention in this issue and you'll be notified when the review is ready! :smile:

**Comment by bvishal8510** [comment]
@madiedgar may I do this?

**Comment by madiedgar** [comment]
Absolutely! That would be amazing @bvishal8510!

**Comment by madiedgar** [comment]
I apologize for my ignorance @bvishal8510, but would love to learn a little more! 

This dialect was suggested in another issue (which is amazing), but it's not currently in `legesher-translations/locale/dialect-list.yml`. The source we first curated the list from was a starting point, but curious if it be referenced to as another name. If not, could you add the dialect to the `dialect-list.yml` file following the conventions below? If there is an official abbreviation of the dialect, please use that. Otherwise, please make sure the abbreviation isn't currently listed in the file. 
``` yml
EnglishDialectName: 
  abbreviation: "" 
  localName: ""
```
